const eur = new Intl.NumberFormat('nl-NL', { style: 'currency', currency: 'EUR' });
const initialCategories = ['Boeken', 'Kleding & Mijn Stijl', 'Auto', 'Mylène', 'Vlees', 'Groente & fruit', 'Kaas, zuivel & vis', 'Noot & brood', 'Huisgemaakt & snoep'];
const initialProducts = [
  { id: 1, category: 'Boeken', code: 'B13', title: 'De wondervolle geboorte van ons land', description: 'N. Verdouw', price: 15, image: '' },
  { id: 2, category: 'Boeken', code: 'B14', title: 'Op volle kracht', description: 'M. Kanis · Een spannend verhaal', price: 12.95, image: '' },
  { id: 3, category: 'Boeken', code: 'B15', title: 'Vol verwachting steeds verhuizen', description: 'Jonathan Goforth · J. Kranendonk-Gijssen', price: 10.95, image: '' },
  { id: 4, category: 'Boeken', code: 'B17', title: 'Lammeren in Zijn armen', description: 'B. Hooghwerrf · Verhalen uit het leven van Gods kinderen', price: 14.5, image: '' },
  { id: 5, category: 'Creatief', code: 'C01', title: 'Handgemaakte kaarsenset', description: 'Set van drie sfeervolle kaarsen', price: 8.5, image: '' },
  { id: 6, category: 'Voor thuis', code: 'T01', title: 'Appeltaart voor thuis', description: 'Vers gebakken, ca. 8 punten', price: 9.5, image: '' }
];
let categories = JSON.parse(localStorage.getItem('mk_categories')) || initialCategories;
let products = JSON.parse(localStorage.getItem('mk_products')) || initialProducts;
let cart = JSON.parse(localStorage.getItem('mk_cart')) || {};
let orders = JSON.parse(localStorage.getItem('mk_orders')) || [];
let sponsors = JSON.parse(localStorage.getItem('mk_sponsors')) || { 'Boeken': { name: 'Maatschap van Binsbergen', text: 'Met dank aan onze sponsor voor deze categorie.', image: '' } };
let settings = JSON.parse(localStorage.getItem('mk_settings')) || { deadline: '', eventDate: '', pickupLocation: '', pickupTime: '' };
let activeCategory = 'Alles';
const $ = s => document.querySelector(s);
const save = () => { localStorage.setItem('mk_categories', JSON.stringify(categories)); localStorage.setItem('mk_products', JSON.stringify(products)); localStorage.setItem('mk_cart', JSON.stringify(cart)); localStorage.setItem('mk_orders', JSON.stringify(orders)); localStorage.setItem('mk_sponsors', JSON.stringify(sponsors)); localStorage.setItem('mk_settings', JSON.stringify(settings)); };
if (!localStorage.getItem('mk_catalog_2025_seeded') && Array.isArray(window.catalog2025)) { const codes = new Set(products.map(p => p.code)); products.push(...window.catalog2025.filter(p => !codes.has(p.code))); localStorage.setItem('mk_catalog_2025_seeded', '1'); save(); }
const escapeHtml = s => String(s || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function dateText(value){ if(!/^\d{4}-\d{2}-\d{2}$/.test(value||'')) return 'datum volgt'; return new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`)); }
function renderSettings(){ const deadline=dateText(settings.deadline),eventDate=dateText(settings.eventDate||settings.pickupDate||settings.deliveryDate),location=settings.pickupLocation||'locatie volgt',time=settings.pickupTime||'tijd volgt'; $('#orderDeadline').textContent=deadline; $('#eventDate').textContent=eventDate; $('#pickupLocation').textContent=location; $('#pickupTime').textContent=time; $('#pickupDetails').textContent=`${eventDate}${settings.pickupTime?` · ${settings.pickupTime}`:''} · ${location}`; }

function productImage(product) { return product.image ? `<img src="${product.image}" alt="${escapeHtml(product.title)}">` : `<div class="book-placeholder">${escapeHtml(product.code)}<br><small>${escapeHtml(product.category)}</small></div>`; }
function renderCatalog() {
  $('#categoryFilters').innerHTML = ['Alles', ...categories].map(c => `<button class="${c === activeCategory ? 'active' : ''}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');
  const list = activeCategory === 'Alles' ? products : products.filter(p => p.category === activeCategory);
  $('#productTotal').textContent = `${list.length} artikelen`;
  const sponsor = sponsors[activeCategory], sponsorCard = $('#sponsorCard');
  if (sponsor?.name) { sponsorCard.hidden = false; sponsorCard.classList.add('visible'); sponsorCard.innerHTML = `${sponsor.image ? `<img src="${sponsor.image}" alt="Logo ${escapeHtml(sponsor.name)}">` : ''}<div><span class="eyebrow">MEDE MOGELIJK GEMAAKT DOOR</span><b>${escapeHtml(sponsor.name)}</b><p>${escapeHtml(sponsor.text || '')}</p></div>`; } else { sponsorCard.hidden = true; sponsorCard.classList.remove('visible'); }
  $('#productGrid').innerHTML = list.length ? list.map(p => `<article class="product-card"><div class="product-image">${productImage(p)}</div><div class="product-info"><span class="product-code">${escapeHtml(p.code)} · ${escapeHtml(p.category)}</span><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.description)}</p><div class="product-bottom"><span class="price">${eur.format(p.price)}</span><button class="add-button" data-add="${p.id}">+ Toevoegen</button></div></div></article>`).join('') : '<p>Er zijn nog geen artikelen in deze categorie.</p>';
  document.querySelectorAll('[data-category]').forEach(b => b.onclick = () => { activeCategory = b.dataset.category; renderCatalog(); });
  document.querySelectorAll('[data-add]').forEach(b => b.onclick = () => changeCart(+b.dataset.add, 1));
}
function cartProducts() { return Object.entries(cart).map(([id, quantity]) => ({ product: products.find(p => p.id === +id), quantity })).filter(x => x.product); }
function changeCart(id, delta) { cart[id] = (cart[id] || 0) + delta; if (cart[id] <= 0) delete cart[id]; save(); renderCart(); }
function itemTotal() { return cartProducts().reduce((sum, x) => sum + x.product.price * x.quantity, 0); }
function renderCart() {
  const rows = cartProducts(); const count = rows.reduce((s, x) => s + x.quantity, 0);
  $('#cartCount').textContent = count; $('#cartSubtotal').textContent = eur.format(itemTotal());
  $('#cartItems').innerHTML = rows.length ? rows.map(({product:p, quantity:q}) => `<div class="cart-row"><div><b>${escapeHtml(p.title)}</b><small>${eur.format(p.price)} per stuk</small></div><div><strong>${eur.format(p.price*q)}</strong><div class="quantity"><button data-qty="${p.id}" data-change="-1">−</button><span>${q}</span><button data-qty="${p.id}" data-change="1">+</button></div></div></div>`).join('') : '<p class="empty">Uw mandje is nog leeg.</p>';
  document.querySelectorAll('[data-qty]').forEach(b => b.onclick = () => changeCart(+b.dataset.qty, +b.dataset.change));
}
function setPanel(open) { $('#cartPanel').classList.toggle('open', open); $('#overlay').classList.toggle('open', open); }
function checkoutTotal() { const delivery = document.querySelector('input[name="fulfilment"]:checked')?.value === 'delivery' ? 4 : 0; return itemTotal() + delivery; }
function updateCheckoutTotal() { $('#checkoutTotal').textContent = eur.format(checkoutTotal()); }

function renderAdmin() {
  $('#adminProducts').innerHTML = `<table class="admin-table"><thead><tr><th>Code</th><th>Artikel</th><th>Prijs</th><th></th></tr></thead><tbody>${products.map(p => `<tr><td>${escapeHtml(p.code)}</td><td><b>${escapeHtml(p.title)}</b><br><small>${escapeHtml(p.category)}</small></td><td>${eur.format(p.price)}</td><td><button class="text-button" data-edit-product="${p.id}">Bewerk</button></td></tr>`).join('')}</tbody></table>`;
  $('#adminCategories').innerHTML = `<table class="admin-table"><thead><tr><th>Categorie</th><th></th></tr></thead><tbody>${categories.map((c,i) => `<tr><td>${escapeHtml(c)}</td><td><button class="text-button" data-edit-category="${i}">Naam wijzigen</button> <button class="text-button" data-edit-sponsor="${i}">Sponsor</button> <button class="text-button danger" data-delete-category="${i}">Verwijder</button></td></tr>`).join('')}</tbody></table>`;
  $('#adminOrders').innerHTML = orders.length ? `<table class="admin-table"><thead><tr><th>Datum</th><th>Besteller</th><th>Ontvangst</th><th>Betaling</th><th>Totaal</th></tr></thead><tbody>${orders.map(o => `<tr><td>${o.date}</td><td><b>${escapeHtml(o.name)}</b><br><small>${escapeHtml(o.phone)}</small></td><td>${o.fulfilment === 'delivery' ? 'Bezorgen' : 'Afhalen'}</td><td>${o.payment === 'tikkie' ? 'Tikkie' : 'Contant'}</td><td>${eur.format(o.total)}</td></tr>`).join('')}</tbody></table>` : '<p class="empty">Er zijn nog geen bestellingen.</p>';
  $('#adminGoals').innerHTML = `<table class="admin-table"><thead><tr><th>Doel</th><th>Gebruik</th><th></th></tr></thead><tbody>${window.mkGoals.map((g,i)=>`<tr><td><b>Doel ${i+1}</b><br>${escapeHtml(g.title)}</td><td>${i===0?'Alleen de kaart op de doelenpagina':'Kaart, volledige pagina en afbeelding'}</td><td><button class="text-button" data-edit-goal="${i}">Bewerk</button></td></tr>`).join('')}</tbody></table>`;
  $('#generalForm').deadline.value=/^\d{4}-\d{2}-\d{2}$/.test(settings.deadline||'')?settings.deadline:''; $('#generalForm').eventDate.value=/^\d{4}-\d{2}-\d{2}$/.test(settings.eventDate||settings.pickupDate||settings.deliveryDate||'')?(settings.eventDate||settings.pickupDate||settings.deliveryDate):''; $('#generalForm').pickupLocation.value=settings.pickupLocation||''; $('#generalForm').pickupTime.value=settings.pickupTime||'';
  document.querySelectorAll('[data-edit-product]').forEach(b => b.onclick = () => editProduct(products.find(p => p.id === +b.dataset.editProduct)));
  document.querySelectorAll('[data-edit-category]').forEach(b => b.onclick = () => editCategory(+b.dataset.editCategory));
  document.querySelectorAll('[data-edit-sponsor]').forEach(b => b.onclick = () => editSponsor(categories[+b.dataset.editSponsor]));
  document.querySelectorAll('[data-edit-goal]').forEach(b => b.onclick = () => editGoal(+b.dataset.editGoal));
  document.querySelectorAll('[data-delete-category]').forEach(b => b.onclick = () => { const i = +b.dataset.deleteCategory; if (products.some(p => p.category === categories[i])) return alert('Verplaats of verwijder eerst de artikelen uit deze categorie.'); categories.splice(i,1); save(); renderAdmin(); renderCatalog(); });
}
function showEdit(title, html, onSave) { $('#editTitle').textContent = title; $('#editFields').innerHTML = html; $('#editForm').onsubmit = e => { e.preventDefault(); onSave(new FormData(e.target)); $('#editDialog').close(); }; $('#editDialog').showModal(); }
function editProduct(p) {
  const isNew = !p; p = p || {id: Date.now(), category: categories[0] || '', code: '', title: '', description: '', price: '', image: ''};
  showEdit(isNew ? 'Nieuw artikel' : 'Artikel bewerken', `<div class="edit-grid"><label>Artikelcode<input required name="code" value="${escapeHtml(p.code)}"></label><label>Categorie<select required name="category">${categories.map(c => `<option ${c===p.category?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select></label><label class="full">Titel<input required name="title" value="${escapeHtml(p.title)}"></label><label>Prijs (€)<input required name="price" type="number" step="0.01" min="0" value="${p.price}"></label><label>Afbeelding uploaden<input name="imageFile" type="file" accept="image/*"></label><label class="full">Omschrijving<textarea name="description" rows="3">${escapeHtml(p.description)}</textarea></label></div>`, fd => {
    const commit = image => { const updated = {...p, code:fd.get('code'),category:fd.get('category'),title:fd.get('title'),description:fd.get('description'),price:+fd.get('price'),image:image ?? p.image}; const ix=products.findIndex(x=>x.id===p.id); if(ix>=0) products[ix]=updated; else products.push(updated); save(); renderCatalog(); renderAdmin(); };
    const file = fd.get('imageFile'); if (file?.size) { const reader = new FileReader(); reader.onload = () => commit(reader.result); reader.readAsDataURL(file); } else commit();
  });
}
function editCategory(index) { const current=index === null ? '' : categories[index]; showEdit(current ? 'Categorie bewerken' : 'Nieuwe categorie', `<div class="edit-grid"><label class="full">Naam<input required name="name" value="${escapeHtml(current)}"></label></div>`, fd => { const name=fd.get('name').trim(); if (!name) return; if(index === null) categories.push(name); else { products.forEach(p=>{if(p.category===current)p.category=name}); if(sponsors[current]) { sponsors[name]=sponsors[current]; delete sponsors[current]; } categories[index]=name; } save(); renderCatalog(); renderAdmin(); }); }
function editSponsor(category) { const s=sponsors[category] || {name:'',text:'',image:''}; showEdit(`Sponsor bij ${category}`, `<div class="edit-grid"><label class="full">Naam sponsor<input name="name" value="${escapeHtml(s.name)}"></label><label class="full">Toelichting<textarea name="text" rows="3">${escapeHtml(s.text)}</textarea></label><label class="full">Logo uploaden<input name="imageFile" type="file" accept="image/*"></label></div>`, fd => { const commit=image=>{ sponsors[category]={name:fd.get('name').trim(),text:fd.get('text').trim(),image:image ?? s.image}; save(); renderCatalog(); renderAdmin(); }; const file=fd.get('imageFile'); if(file?.size){const reader=new FileReader();reader.onload=()=>commit(reader.result);reader.readAsDataURL(file)}else commit(); }); }
function editGoal(index) { const g=window.mkGoals[index]; const fields=index===0?`<div class="edit-grid"><label class="full">Titel<input required name="title" value="${escapeHtml(g.title)}"></label><label class="full">Korte tekst op de doelenpagina<textarea required name="preview" rows="5">${escapeHtml(g.preview)}</textarea></label></div>`:`<div class="edit-grid"><label class="full">Titel<input required name="title" value="${escapeHtml(g.title)}"></label><label class="full">Volledige tekst <small>Een lege regel maakt een nieuwe alinea.</small><textarea required name="body" rows="11">${escapeHtml(g.body)}</textarea></label><label class="full">Afbeelding uploaden<input name="imageFile" type="file" accept="image/*"></label></div>`; showEdit(`Doel ${index+1} bewerken`,fields,fd=>{const commit=image=>{window.mkGoals[index]=index===0?{title:fd.get('title').trim(),preview:fd.get('preview').trim()}:{title:fd.get('title').trim(),body:fd.get('body').trim(),image:image??g.image};window.saveGoals();renderAdmin();};const file=fd.get('imageFile');if(index===1&&file?.size){const reader=new FileReader();reader.onload=()=>commit(reader.result);reader.readAsDataURL(file)}else commit();});}
function exportOrders() { if(!orders.length) return alert('Er zijn nog geen bestellingen om te downloaden.'); const header=['Datum','Naam','Adres','Postcode','Woonplaats','Telefoon','Tikkie telefoon','Ontvangst','Betaling','Artikelen','Totaal']; const lines=[header,...orders.map(o=>[o.date,o.name,o.address,o.postal,o.city,o.phone,o.tikkiePhone,o.fulfilment==='delivery'?'Bezorgen':'Afhalen',o.payment==='tikkie'?'Tikkie':'Contant',o.items.map(i=>`${i.quantity}x ${i.title}`).join(' | '),o.total.toFixed(2)])].map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(';')); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'})); a.download='marktkrant-bestellingen.csv'; a.click(); URL.revokeObjectURL(a.href); }

$('#cartToggle').onclick=()=>setPanel(true); $('#overlay').onclick=()=>setPanel(false);
$('#checkoutStart').onclick=()=>{ if(!cartProducts().length) return; setPanel(false); updateCheckoutTotal(); $('#checkoutDialog').showModal(); };
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{ const dialog=b.closest('dialog'); if(dialog)dialog.close(); else setPanel(false); });
document.querySelectorAll('input[name="fulfilment"]').forEach(i=>i.onchange=updateCheckoutTotal);
document.querySelectorAll('input[name="payment"]').forEach(i=>i.onchange=()=>$('#tikkieField').style.display=document.querySelector('input[name="payment"]:checked').value==='tikkie'?'flex':'none');
$('#checkoutForm').onsubmit=e=>{ e.preventDefault(); const fd=new FormData(e.target), f=Object.fromEntries(fd); const order={...f,date:new Date().toLocaleDateString('nl-NL'),items:cartProducts().map(x=>({title:x.product.title,quantity:x.quantity,price:x.product.price})),total:checkoutTotal()}; orders.unshift(order); cart={}; save(); renderCart(); renderAdmin(); $('#checkoutDialog').close(); const eventDate=dateText(settings.eventDate); $('#confirmationText').textContent=`Dank u, ${order.name}. ${order.payment==='tikkie'?'Na de sluitingsdatum ontvangt u een Tikkie.':'U betaalt contant bij de '+(order.fulfilment==='delivery'?'aflevering.':'afhaalplek.')}`; $('#confirmationSummary').innerHTML=`<h3>Uw bestelling</h3>${order.items.map(i=>`<div><span>${i.quantity}× ${escapeHtml(i.title)}</span><b>${eur.format(i.price*i.quantity)}</b></div>`).join('')}<div class="summary-total"><span>Totaal</span><b>${eur.format(order.total)}</b></div><p><b>${order.fulfilment==='delivery'?'Bezorging':'Afhalen'}</b><br>${order.fulfilment==='delivery'?`Op ${eventDate}`:`${eventDate}${settings.pickupTime?` · ${settings.pickupTime}`:''}<br>${escapeHtml(settings.pickupLocation||'')}`}</p>${order.email?'<p class="email-note">In de uiteindelijke online versie wordt dit overzicht ook naar dit e-mailadres gestuurd.</p>':''}`; $('#confirmationDialog').showModal(); e.target.reset(); };
function openAdmin(){ renderAdmin(); $('#adminDialog').showModal(); }
$('#adminToggle').onclick=()=>{ if(sessionStorage.getItem('mk_admin_session') || localStorage.getItem('mk_admin_session')) return openAdmin(); $('#loginError').textContent=''; $('#adminLoginDialog').showModal(); };
$('#adminLoginForm').onsubmit=e=>{ e.preventDefault(); const fd=new FormData(e.target), password=fd.get('password'); if(password !== (localStorage.getItem('mk_admin_password') || 'marktkrant2026')) { $('#loginError').textContent='De beheercode is niet juist.'; return; } (fd.get('remember') ? localStorage : sessionStorage).setItem('mk_admin_session','1'); e.target.reset(); $('#adminLoginDialog').close(); openAdmin(); };
$('#generalForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);settings={deadline:fd.get('deadline'),eventDate:fd.get('eventDate'),pickupLocation:fd.get('pickupLocation').trim(),pickupTime:fd.get('pickupTime').trim()};save();renderSettings();};
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{ document.querySelectorAll('.admin-tabs button,.admin-panel').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#'+b.dataset.tab+'Tab').classList.add('active'); });
$('#newProduct').onclick=()=>editProduct(null); $('#newCategory').onclick=()=>editCategory(null); $('#exportOrders').onclick=exportOrders;
renderSettings(); renderCatalog(); renderCart();
